services:
  app1:
    build:
      context: .
    container_name: app1
    expose:
      - "80"
  app2:
    build:
      context: .
    container_name: app2
    expose:
      - "80"
  app3:
    build:
      context: .
    container_name: app3
    expose:
      - "80"
  nginx:
    image: nginx:1.29.3-alpine
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3