services:
  app1:
    build: .
    environment:
      - VITE_APP_NAME=App1
    command: ["npm", "run", "dev", "--", "--port", "5173", "--host"]
    ports:
      - "5173:5173"
  app2:
    build: .
    environment:
      - VITE_APP_NAME=App2
    command: ["npm", "run", "dev", "--", "--port", "5174", "--host"]
    ports:
      - "5174:5174"
  app3:
    build: .
    environment:
      - VITE_APP_NAME=App3
    command: ["npm", "run", "dev", "--", "--port", "5175", "--host"]
    ports:
      - "5175:5175"
  nginx:
    image: nginx:1.29.3-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
    container_name: nginx-proxy