version: "2.40.3"
services:
  app1:
    build: .
    environment:
      - VITE_APP_NAME=App1
    ports:
      - "5173:5173"
  app2:
    build: .
    environment:
      - VITE_APP_NAME=App2
    ports:
      - "5174:5173"
  app3:
    build: .
    environment:
      - VITE_APP_NAME=App3
    ports:
      - "5175:5173"